language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # Additional components
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22
    # - sys-img-x86-android-17

sudo: required

jdk:
  - oraclejdk8

install: true

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease --stacktrace