language: android
android:
  components:
  - android-22
  - build-tools-22.0.1
  - extra-android-support
  - extra
  - add-on
sudo: required
jdk:
- oraclejdk8
install: true
script:
- "./gradlew assembleRelease --stacktrace"
before_script:
- chmod +x gradlew
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: jui/x3XvqKOOhkaAGWfkmV7CHwDi9rbtXmvFYS2axyWXmeZjuUzNNzyulZIEfpRVU9fHKaw8CxcZwVi/+WbkmNxOl6Mpg1E6lkxXVnN5sUb6icTSToBIYPJZyVHvuzJdmwMSFL1GDxYbADGkxjVA8NishcHhg+IULDfDVRrAIfgPPEz2AGDAFaaTBQI8Rdeuig9J9uVug8rBcEwhkcQdwmy573l2Os5HBb+Cg1JA8wQFcz1SStlOLORSMIG93DhjaeqPzwy0OtAd3N2CQUTu4ZJsKZq2jQVOpBLvy/1q1HhuKfeLZoISMTN8Pmv0WdQWeZ7xW+ckGgbYc8FbRkx5Q52UcUjOFUDDhzJeHEqOAXKGAlLsUvoH7HI/cuLbxF6lTmr72T+HiliIoZwI8WSdzjAYt3itFykH0g9IhYYwgpPr6vcqa36tpR1LAJ+mN+R3R+sxERb0iSc2/j0w7JBhFBMiRuM+nqyFrJvzfbn7v7tAzhkGFcopwQFVAykwg9sZzI+wBGFwiZVkiBnDnahRIohsw7f634A9CSb+r1pTM7akJe6xSW9/+isFa7cf9+zm0lrs9DWsPSJmxF0t3A1AiGxROUhM/CLPrpUTRRJKlgaK7HbUvfpI5AIkmgA6CAg6GoudO0bVV4eHoMUoAH8FJf1bWqCmxBf9GIhq9aieqxE=
  file: $TRAVIS_BUILD_DIR/app/build/outputs/aar/bigfinancekeyboard-release.aar
  on:
    repo: alanbertadev/androidbigfinancekeyboard
    branch: production
